### ISSUE TITLE
Canary release does not include a manifest

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin-trigger-cron#4]
![image](https://github.com/fermyon/spin-trigger-cron/assets/865538/093194fa-131d-4d6d-b23c-6bb8ac3318fc)

This causes the install instruiction in the README to fail with a 404.

**Comment by karthik2804** [comment]
Not sure why the manifest did not get published. I am going to rerun the action. I vaguely remember restarting the action or something along the lines in the past. 
If a rerun does not fix it I will take a peek into it.

**Comment by itowlson** [comment]
Thanks!
